const weddingDate=new Date('2027-09-25T16:00:00+02:00');
const events=[
 {year:'31 Desember 2022',title:'Waar alles begin het',text:'Ons het mekaar op die mees onverwagte manier ontmoet—die regte plek op presies die regte tyd. Op Oujaarsaand het ons vir die eerste keer die wêreld in mekaar se oë raakgesien. Wat as ’n onverwagte ontmoeting begin het, het vinnig in iets besonders gegroei. Vier maande later het ons besluit om hierdie avontuur saam aan te pak. Die begin van ons mooiste liefdesverhaal.',image:'assets/Photo1.jpeg'},
 {year:'2023',title:'Ons eerste avonture',text:'Ons het elke moontlike oomblik saam gekoester. Dit was ’n jaar vol kosbare herinneringe saam met vriende en familie. Van lang padritte en spontane avonture tot rustige staptogte in die bos. Selfs die eenvoudigste oomblikke het besonders geword, net omdat ons dit saam kon beleef.',image:'assets/Photo2.png'},
 {year:'2024',title:'Saam deur elke seisoen',text:'Deur lang afstande en moeilike tye het ons altyd saamgestaan en saam sterker geword. Ons het mekaar ondersteun, aangemoedig en gehelp groei. Vir onsself, vir mekaar en vir die lewe wat ons saam bou.',image:'assets/Photo3.jpeg'},
 {year:'29 Desember 2025',title:'Die maklikste “ja”',text:'Die maklikste “ja” en ’n geluk wat ons skaars in woorde kon vasvang. Dit was meer as net ’n vraag en ’n antwoord. Dit was ons belofte om mekaar aan te hou kies, saam te groei en elke nuwe hoofstuk hand aan hand te skryf. Skielik het ons droom van vir altyd ’n datum gekry.',image:'assets/Photo4.jpeg'}];
document.querySelector('#timeline').innerHTML=events.map((e,i)=>`<article><div class="memory"><img src="${e.image}" alt="Replace with your memory photograph"><span>${String(i+1).padStart(2,'0')}</span></div><div class="memory-copy"><em>${e.year}</em><h3>${e.title}</h3><p>${e.text}</p></div></article>`).join('');
function show(name){document.querySelector('#envelope').classList.remove('active');document.querySelector('#site').classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector(`#${name}`).classList.add('active');history.replaceState(null,'',`#${name}`);scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#open').addEventListener('click',()=>{const envelope=document.querySelector('#envelope');const site=document.querySelector('#site');envelope.classList.add('opening');setTimeout(()=>envelope.classList.add('leaving'),700);setTimeout(()=>{site.classList.add('reveal-from-envelope');show('home');setTimeout(()=>site.classList.remove('reveal-from-envelope'),1000)},1250)});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{show('home');setTimeout(()=>document.querySelector('.countdown-section').scrollIntoView({behavior:'smooth'}),80)}));
function tick(){let d=Math.max(0,weddingDate-Date.now());let v={days:Math.floor(d/86400000),hours:Math.floor(d/3600000%24),minutes:Math.floor(d/60000%60),seconds:Math.floor(d/1000%60)};Object.entries(v).forEach(([k,n])=>document.querySelector(`#${k}`).textContent=String(n).padStart(2,'0'))}tick();setInterval(tick,1000);if(['home','story','engagement'].includes(location.hash.slice(1)))show(location.hash.slice(1));
