const weddingDate=new Date('2027-09-25T16:00:00+02:00');
const events=[
 {year:'31 Desember 2022',title:'Waar alles begin het',text:'Ons het mekaar op die mees onverwagte manier ontmoet. Sommige mense sal sê dit was die regte plek op presies die regte tyd, maar vir ons voel dit asof die lewe geweet het ons paaie moes kruis. Op Oujaarsaand het ons vir die eerste keer die wêreld in mekaar se oë raakgesien. Wat as ’n onverwagte ontmoeting begin het, het vinnig in iets besonders gegroei. Vier maande later het hy my gevra om sy meisie te wees, en sonder dat ons dit toe besef het, het ons mooiste avontuur begin. Dit was die begin van ons lewe saam. ’n lewe vol liefde, nuwe herinneringe en elke avontuur hand aan hand.',image:'assets/Photo1.jpeg'},
 {year:'2023',title:'Ons eerste avonture',text:'Ons het omtrent alles saam gedoen en elke moontlike oomblik in mekaar se geselskap deurgebring. Dit was ’n jaar vol onvergeetlike herinneringe saam met vriende en familie. Van lang padritte en spontane avonture tot rustige staptogte in die bos. Selfs die eenvoudigste oomblikke het spesiaal geword, bloot omdat ons dit saam kon beleef.',image:'assets/Photo2.png'},
 {year:'2024',title:'Saam deur elke seisoen',text:'Ten spyte van die lang afstande en moeilike tye het ons altyd saamgestaan. Ons het mekaar gedra wanneer dinge swaar geraak het, mekaar aangemoedig en saam sterker geword. Deur alles het ons mekaar gehelp om die beste weergawes van onsself te word nie net vir onsself nie, maar ook vir mekaar en vir die lewe wat ons saam bou.',image:'assets/Photo3.jpeg'},
 {year:'29 Desember 2025',title:'Die maklikste “ja”',text:'Dit was die maklikste “ja” wat ek nog ooit gesê het.Daardie oomblik het ’n soort geluk gebring wat moeilik is om in woorde vas te vang. ’n hart wat oorloop, trane van vreugde en die besef dat ons vir altyd nou werklik begin. Dit was meer as net ’n vraag en ’n antwoord. Dit was ’n belofte om aan te hou kies, aan te hou groei en elke nuwe hoofstuk van ons lewe saam te skryf. En skielik het die toekoms waaroor ons nog altyd gedroom het, ’n datum gekry.',image:'assets/Photo4.jpeg'}];
document.querySelector('#timeline').innerHTML=events.map((e,i)=>`<article><div class="memory"><img src="${e.image}" alt="Replace with your memory photograph"><span>${String(i+1).padStart(2,'0')}</span></div><div class="memory-copy"><em>${e.year}</em><h3>${e.title}</h3><p>${e.text}</p></div></article>`).join('');
function show(name){document.querySelector('#envelope').classList.remove('active');document.querySelector('#site').classList.add('active');document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector(`#${name}`).classList.add('active');history.replaceState(null,'',`#${name}`);scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#open').addEventListener('click',()=>{document.querySelector('#envelope').classList.add('opening');setTimeout(()=>show('home'),1100)});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.page)));
function tick(){let d=Math.max(0,weddingDate-Date.now());let v={days:Math.floor(d/86400000),hours:Math.floor(d/3600000%24),minutes:Math.floor(d/60000%60),seconds:Math.floor(d/1000%60)};Object.entries(v).forEach(([k,n])=>document.querySelector(`#${k}`).textContent=String(n).padStart(2,'0'))}tick();setInterval(tick,1000);if(['home','story','engagement'].includes(location.hash.slice(1)))show(location.hash.slice(1));
